jobs:
  build:
    name: Build native libraries
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2.0
      with:
        cmake-version: 3.16.x
    - continue-on-error: true
      env:
        OCI_EXE: docker
      name: Build native libraries
      run: make clean-native native-all
    - continue-on-error: true
      if: ${{ github.event_name != 'pull_request' }}
      name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        branch: update-native-libs
        commit-message: Update native libraries for ${{ github.sha }}
        labels: library-update
        title: Update native libraries
name: Build Native
on:
  repository_dispatch:
    types: trigger-ga___build-native.yml
