jobs:
  publish_jvm:
    name: Publish
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 10000
    - continue-on-error: true
      run: git fetch --tags -f
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '11'
    - continue-on-error: true
      env:
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
      name: Setup GPG
      run: echo $PGP_SECRET | base64 --decode | gpg --import --batch --yes
    - continue-on-error: true
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      name: Build bundle
      run: './sbt publishSigned

        '
    - continue-on-error: true
      env:
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASS }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USER }}
      name: Release to Sonatype
      run: ./sbt sonatypeBundleRelease
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
