jobs:
  release:
    name: Create a new release note
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Create a release note
      run: 'gh release create "$GITHUB_REF_NAME" --repo="$GITHUB_REPOSITORY" --generate-notes

        '
name: Release Note
on:
  repository_dispatch:
    types: trigger-ga___release-note.yml
