jobs:
  code_format:
    name: code format
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: scalafmt test
      run: ./sbt scalafmtCheckAll
  test-jdk:
    name: test jdk${{ matrix.version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.version }}
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-jdk${{ matrix.version }}-${{ hashFiles('**/*.sbt') }}
        path: ~/.cache
        restore-keys: ${{ runner.os }}-jdk${{ matrix.version }}-
    - continue-on-error: true
      name: Test
      run: ./sbt test
    strategy:
      matrix:
        version:
        - '8'
        - '11'
        - '17'
        - '21'
name: CI
on:
  repository_dispatch:
    types: trigger-ga___test.yml
